const WorkersDummyData = [

    {   
        id:"1",
        img:"/avatar1.jpg",
        name:"Abebe Kebede",
        location:"6 kilo",
        salary:"500",
        salaryrate:"hourly",
        skill:"plumber",
        rate:3
    },
    {
        id:"2",
        img:"/avatar1.jpg",
        name:"chala Kebede",
        location:"4 kilo",
        salary:"6000",
        salaryrate:"monthly",
        skill:"labor",
        rate:2
    },
    {
        id:"3",
        img:"/avatar1.jpg",
        name:"Abebe Kebede",
        location:"6 kilo",
        salary:"500",
        salaryrate:"hourly",
        skill:"plumber",
        rate:5
    },
    {id:"4",
        img:"/avatar1.jpg",
        name:"Abebe Kebede",
        location:"6 kilo",
        salary:"500",
        salaryrate:"hourly",
        skill:"plumber",
        rate:5
    },
    {id:"5",
        img:"/avatar1.jpg",
        name:"Abebe Kebede",
        location:"6 kilo",
        salary:"500",
        salaryrate:"hourly",
        skill:"plumber",
        rate:3
    },
    {id:"6",
        img:"/avatar1.jpg",
        name:"chala Kebede",
        location:"4 kilo",
        salary:"6000",
        salaryrate:"monthly",
        skill:"labor",
        rate:2
    },
    {id:"7",
        img:"/avatar1.jpg",
        name:"Abebe Kebede",
        location:"6 kilo",
        salary:"500",
        salaryrate:"hourly",
        skill:"plumber",
        rate:5
    },
    {id:"8",
        img:"/avatar1.jpg",
        name:"Abebe Kebede",
        location:"6 kilo",
        salary:"500",
        salaryrate:"hourly",
        skill:"plumber",
        rate:5
    },
    {id:"9",
        img:"/avatar1.jpg",
        name:"Abebe Kebede",
        location:"6 kilo",
        salary:"500",
        salaryrate:"hourly",
        skill:"plumber",
        rate:3
    },
    {id:"11",
        img:"/avatar1.jpg",
        name:"chala Kebede",
        location:"4 kilo",
        salary:"6000",
        salaryrate:"monthly",
        skill:"labor",
        rate:2
    },
    {id:"12",
        img:"/avatar1.jpg",
        name:"Abebe Kebede",
        location:"6 kilo",
        salary:"500",
        salaryrate:"hourly",
        skill:"plumber",
        rate:5
    },
    {id:"13",
        img:"/avatar1.jpg",
        name:"Abebe Kebede",
        location:"6 kilo",
        salary:"500",
        salaryrate:"hourly",
        skill:"plumber",
        rate:5
    },

];

export default WorkersDummyData;